# Ansible host

- !host ansible.ee

- !grant
  role: !layer prod/ansible/v1
  member: !host ansible.ee

- !host
  id: analytics-001.itr.myorg.com
  annotations:
    puppet: "true"

- !host
  id: sample-cf-host
  annotations:
    cloudfoundry: "true"

- !host
  id: sample-pcf-host
  annotations:
    pivotalcloudfoundry: "true"

- !host
  id: sample-kubernetes-host
  annotations:
    kubernetes: "true"
    
- !host
  id: sample-openshift-host
  annotations:
    openshift: "true"

- !grant
  role: !layer prod/analytics/v1
  member: !host analytics-001.itr.myorg.com

- !host analytics-002.itr.myorg.com

- !grant
  role: !layer prod/analytics/v1
  member: !host analytics-002.itr.myorg.com

- !host analytics-003.itr.myorg.com

- !grant
  role: !layer prod/analytics/v1
  member: !host analytics-003.itr.myorg.com

- !host app-001.itp.myorg.com

- !grant
  role: !layer prod/frontend/v1
  member: !host app-001.itp.myorg.com

- !host app-002.itp.myorg.com

- !grant
  role: !layer prod/frontend/v1
  member: !host app-002.itp.myorg.com

- !host app-003.itp.myorg.com

- !grant
  role: !layer prod/frontend/v1
  member: !host app-003.itp.myorg.com

- !host app-004.itp.myorg.com

- !grant
  role: !layer prod/frontend/v1
  member: !host app-004.itp.myorg.com

- !host app-005.itp.myorg.com

- !grant
  role: !layer prod/frontend/v1
  member: !host app-005.itp.myorg.com

- !host cloud.itp.myorg.com

- !grant
  role: !layer prod/openvpn/v1
  member: !host cloud.itp.myorg.com

- !host office.itp.myorg.com

- !grant
  role: !layer prod/openvpn/v1
  member: !host office.itp.myorg.com

- !host userdb-01.itp.myorg.com

- !grant
  role: !layer prod/user-database/v1
  member: !host userdb-01.itp.myorg.com

- !host userdb-02.itp.myorg.com

- !grant
  role: !layer prod/user-database/v1
  member: !host userdb-02.itp.myorg.com

- !host executor-ubuntu-01.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-ubuntu-01.itci.myorg.com

- !host executor-ubuntu-02.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-ubuntu-02.itci.myorg.com

- !host executor-centos-01.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-centos-01.itci.myorg.com

- !host executor-darwin-01.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-darwin-01.itci.myorg.com

- !host executor-windows-01.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-windows-01.itci.myorg.com

- !host executor-testing.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/executors
  member: !host executor-testing.itci.myorg.com

- !host admin.itp.myorg.com

- !grant
  role: !layer prod/admin-ui/v1
  member: !host admin.itp.myorg.com

- !host bastion.itp.myorg.com

- !grant
  role: !layer prod/bastion/v1
  member: !host bastion.itp.myorg.com

- !host salt-master.itp.myorg.com

- !grant
  role: !layer prod/salt/v1
  member: !host salt-master.itp.myorg.com

- !host jenkins-master-01.itci.myorg.com

- !grant
  role: !layer ci/jenkins/v1/master
  member: !host jenkins-master-01.itci.myorg.com

